apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sagatxs
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: 10.42.2.127:6379
  - name: redisPassword
    secretKeyRef:
        name: redis
        key: redis-password
    