apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sagatxs
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: 10.42.2.89:6379
  - name: redisPassword
    value: "m7F88eHedz%"
